### ISSUE TITLE
Support for node v4

### ISSUE THREAD

**Issue by baskin** [vaderSentiment/vaderSentiment-js#1]
Hi,
I'm using serverless webtask.io to run my node functions. Unfortunately, webtask.io supports node v4.8.7 and it seems vaderSentiment doesn't work with the version.

/usr/local/lib/node_modules/vader-sentiment/src/vaderSentiment.js:216
const negated = (input_words, include_nt = true) => {
                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/vader-sentiment/src/index.js:21:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Any chance this can be fixed?

**Comment by nimaeskandary** [comment]
Interesting will look into this, may have to be compiled to es5

**Comment by nimaeskandary** [comment]
@baskin published version 1.1.0, can you try reinstalling/ updating the version in your package.json? This would use es5 code instead of es6. Also slightly modified the readme for usage

**Comment by baskin** [comment]
Thanks for the quick update @nimaeskandary 

However, now I get:

node sentiment-test.js
/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1
(function (exports, require, module, __filename, __dirname) { exports.SentimentIntensityAnalyzer=function(e){var s={};function i(r){if(s[r])return s[r].exports;var t=s[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}return i.m=e,i.c=s,i.d=function(e,s,r){i.o(e,s)||Object.defineProperty(e,s,{configurable:!1,enumerable:!0,get:r})},i.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},i.n=function(e){var s=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(s,"a",s),s},i.o=function(e,s){return Object.prototype.hasOwnProperty.call(e,s)},i.p="",i(i.s=2)}([function(e,s,i){"use strict";Object.defineProperty(s,"__esModule",{value:!0});s.lexicon={"$:":-1.5,"%)":-.4,"%-)":-1.5,"&-:":-.4,"&:":-.7,"( '}{' )":1.6,"(%":-.9,"('-:":2.2,"(':":2.3,"((-:":2.1,"(*":1.1,"(-%":-.7,"(-*":1.3,"(-:":1.6,"(-:0":2.8,"(-:<":-.4,"(-:o":1.5,"(-:O":1.5,"(-:{":-.1,"(-:|>*":1.9,"(-;":1.3,"(-;

TypeError: Cannot supply flags when constructing one RegExp from another
    at new RegExp (native)
    at Object.exports.SentimentIntensityAnalyzer.Object.defineProperty.value (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:103771)
    at i (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:206)
    at Object.<anonymous> (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:109959)
    at i (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:206)
    at exports.SentimentIntensityAnalyzer.Object.defineProperty.value (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:620)
    at Object.<anonymous> (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:629)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by nimaeskandary** [comment]
published version 1.1.1, seems the way I was making a regex was not backwards compatible. Let me know if you have any more issues, tested this locally with your version of node and it seems to do the trick

**Comment by baskin** [comment]
Now I get:
```
TypeError: e.includes is not a function
    at s.negated (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:105477)
```

Detailed stack:
```
/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1
(function (exports, require, module, __filename, __dirname) { exports.SentimentIntensityAnalyzer=function(e){var s={};function i(r){if(s[r])return s[r].exports;var t=s[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}return i.m=e,i.c=s,i.d=function(e,s,r){i.o(e,s)||Object.defineProperty(e,s,{configurable:!1,enumerable:!0,get:r})},i.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},i.n=function(e){var s=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(s,"a",s),s},i.o=function(e,s){return Object.prototype.hasOwnProperty.call(e,s)},i.p="",i(i.s=2)}([function(e,s,i){"use strict";Object.defineProperty(s,"__esModule",{value:!0});s.lexicon={"$:":-1.5,"%)":-.4,"%-)":-1.5,"&-:":-.4,"&:":-.7,"( '}{' )":1.6,"(%":-.9,"('-:":2.2,"(':":2.3,"((-:":2.1,"(*":1.1,"(-%":-.7,"(-*":1.3,"(-:":1.6,"(-:0":2.8,"(-:<":-.4,"(-:o":1.5,"(-:O":1.5,"(-:{":-.1,"(-:|>*":1.9,"(-;":1.3,"(-;

TypeError: e.includes is not a function
    at s.negated (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:105477)
    at Function.s.SentimentIntensityAnalyzer.r.value (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:108696)
    at Function.s.SentimentIntensityAnalyzer.r.value (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:107557)
    at Function.s.SentimentIntensityAnalyzer.r.value (/usr/local/lib/node_modules/vader-sentiment/build/vaderSentiment.bundle.js:1:107155)
    at /Users/bhupi/repo/nooz/webtask/sentiment-test.js:24:51
    at Array.forEach (native)
    at Object.<anonymous> (/Users/bhupi/repo/nooz/webtask/sentiment-test.js:23:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by nimaeskandary** [comment]
@baskin Checked it out and Array.prototype.includes and String.prototype.includes are not implemented in all environments. Replaced that logic with `indexOf`. Published 1.1.2 if you want to give it a shot, may run into similar problems though with some other newer functions

**Comment by baskin** [comment]
Works now. Perfect! Much appreciated :)

**Comment by nimaeskandary** [comment]
@baskin Glad to hear it!
